-- Magnitude Analysis
-- Compare the measure values by categories
-- Find total customers by country
SELECT 
    country, 
    COUNT(customer_key) AS number_of_customers 
FROM gold.dim_customers
GROUP BY country
ORDER BY number_of_customers DESC


-- Find total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS number_of_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY number_of_customers DESC


-- Find total products by category
SELECT
    category,
    COUNT(product_key) AS number_of_products
FROM gold.dim_products
GROUP BY category
ORDER BY number_of_products DESC


-- What is the average costs in each category?
SELECT 
    category,
    ROUND(AVG(cost), 2) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC


-- What is the total revenue generated for each category?
SELECT
    dp.category,
    SUM(fs.sales_amount) AS total_sales
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products dp ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY total_sales DESC


-- Find the total revenue generated by each customer
SELECT
    dc.customer_number,
    CONCAT(dc.first_name, ' ', dc.last_name) AS customer_name,
    SUM(fs.sales_amount) AS total_revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc ON fs.customer_key = dc.customer_key
GROUP BY dc.customer_number, CONCAT(dc.first_name, ' ', dc.last_name)
ORDER BY total_revenue DESC


-- What is the distribution of sold items across each country for Water Bottle - 30 oz. ?
SELECT
    dc.country,
    dp.product_name,
    COUNT(fs.product_key) AS number_of_products
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc ON fs.customer_key = dc.customer_key
LEFT JOIN gold.dim_products dp ON fs.product_key = dp.product_key
WHERE product_name = 'Water Bottle - 30 oz.'
GROUP BY dc.country, dp.product_name
ORDER BY dc.country ASC, number_of_products DESC 